name: update

on:
  workflow_dispatch:
  schedule:
    - cron: "30 16 * * WED"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ env.R_VERSION }}

      # Load libraries
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          Rscript -e 'install.packages(c("tidyverse", "dplyr", "lubridate", "tidyr", "janitor", "Rcpp", "s2", "sf"))'
          
      # Run scripts
      - name: Cancelled services
        run: Rscript -e 'source("script/main-care-inspectorate.R')'

      # Commit & push
      - name: Commit files
        run: |
          git config --local user.name "actions-user"
          git config --local user.email "actions@github.com"
          git add data/*
          git commit -m "GH ACTION Headlines $(date)"
          git push origin main
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
